### ISSUE TITLE
Using require.js before mat element causes error.

### ISSUE THREAD

**Issue by gaurav21r** [expandjs/expandjs.github.io#2]
Whenever we include `requireJS` **before** ExapndJS
```html
<script src="../../bower_components/requirejs/require.js"></script>
<link rel="import" href="../../bower_components/mat-tabs/mat-tabs.html">
<link rel="import" href="../../bower_components/mat-tabs/mat-tab.html">
<link rel="import" href="../../bower_components/mat-pages/mat-pages.html">
```
![mat](https://cloud.githubusercontent.com/assets/1716462/10188250/7b8d6022-677b-11e5-872d-df1ae45b9af1.JPG)

Chrome throws up an `XP not defined` error.

Works fine if it is after. But RequireJS is the defacto module loader for AMD and one of the most popular loaders overall. So I think MatJS should really support this Use case!

**Comment by gaurav21r** [comment]
Infact using **any** AMD Loader is causing this error. I tried it with Dojo too! Is `require()` being defined within expand.js somewhere?

**Comment by Pupix** [comment]
We are using browserify to port the node.js module to the browser. It may be using a require method internally.

For the moment you can keep loading requirejs after XP. We are looking for a solution for this, suggestions are welcome.

**Comment by Pupix** [comment]
There indeed seems to be a problemwith browserify and requireJS https://github.com/substack/node-browserify/issues/790

**Comment by gaurav21r** [comment]
But it seems that in production, ie in the `dist/` folder, you are accounting for AMD loaders, https://github.com/expandjs/expandjs/blob/master/dist/expandjs.js#L1 

I am loading `require.js` later only, unfortunately having a `<script>` between our imports is really causing havoc on our `Grunt` based build process :sob:

**Comment by Pupix** [comment]
That accounts for UMD loaders, not AMD.

**Comment by Pupix** [comment]
Issue fixed in [v0.9.10](https://github.com/expandjs/expandjs/releases/tag/v0.9.10), get the new version and you should be all right.

Cheers!

**Comment by gaurav21r** [comment]
@Pupix Thats was incredibly fast! Thanks :smiley: ! What was the fix? Can you link the commit? Also can this be **upstreamed** to substack/node-browserify#790 ?

**Comment by Pupix** [comment]
The fix was short-circuiting the way browserify's `--standalone` option works. It assigns the defined name to the `window` or to a module loader, if it finds one.

The problem was that our custom elements must access `XP` from the `window`, but `RequireJS` was blocking `XP` from reaching . All we had to do was bypass the module loader check and let browserify assign `XP` dirrectly to the `window`.

[The commit.](https://github.com/expandjs/expandjs/commit/32765905ea2cb0815f115867e11db192856541e5)

**Comment by gaurav21r** [comment]
Cool @Pupix Thanks :+1:
